CREATE DATABASE TripDb

GO

USE TripDb

CREATE TABLE [User](
Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
FirstName NVARCHAR(20) NOT NULL,
LastName NVARCHAR(40) NOT NULL,
DOB DATE NOT NULL,
[Address] NVARCHAR(60) NOT NULL,
)

CREATE TABLE Passport(
Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
PassportNumber NVARCHAR(9) NOT NULL,
[Address] NVARCHAR(60) NOT NULL,
ExpirationDate DATE NOT NULL
)

CREATE TABLE Trip(
Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
Budget INT,
StartDestination NVARCHAR(40) NOT NULL,
EndDestination NVARCHAR(40),
TravelMode NVARCHAR(20) NOT NULL,
StartDate DATE,
EndDate DATE
)

CREATE TABLE Hotel(
Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
CheckInDate DATE,
CheckOutDate DATE,
CostPerNight SMALLMONEY,
[Address] NVARCHAR(60) NOT NULL,
PhoneNumber NVARCHAR(50) NOT NULL
)

GO

ALTER TABLE [User]
ADD PassportId INT FOREIGN KEY REFERENCES Passport(Id)

GO

ALTER TABLE Passport
ADD UserId INT FOREIGN KEY REFERENCES [User](Id)

GO

ALTER TABLE Trip
ADD UserId INT FOREIGN KEY REFERENCES [User](Id)

GO

CREATE TABLE TripHotel(
Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
TripId INT FOREIGN KEY REFERENCES Trip(Id),
HotelId INT FOREIGN KEY REFERENCES Hotel(Id)
)